/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as EpgRouteImport } from './routes/epg'
import { Route as EventsRouteImport } from './routes/events'
import { Route as JellyfinRouteImport } from './routes/jellyfin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SourcesRouteImport } from './routes/sources'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const EpgRoute = EpgRouteImport.update({
  id: '/epg',
  path: '/epg',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const JellyfinRoute = JellyfinRouteImport.update({
  id: '/jellyfin',
  path: '/jellyfin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRoute
  '/epg': typeof EpgRoute
  '/events': typeof EventsRoute
  '/jellyfin': typeof JellyfinRoute
  '/login': typeof LoginRoute
  '/sessions': typeof SessionsRoute
  '/sources': typeof SourcesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRoute
  '/epg': typeof EpgRoute
  '/events': typeof EventsRoute
  '/jellyfin': typeof JellyfinRoute
  '/login': typeof LoginRoute
  '/sessions': typeof SessionsRoute
  '/sources': typeof SourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRoute
  '/epg': typeof EpgRoute
  '/events': typeof EventsRoute
  '/jellyfin': typeof JellyfinRoute
  '/login': typeof LoginRoute
  '/sessions': typeof SessionsRoute
  '/sources': typeof SourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/channels'
    | '/epg'
    | '/events'
    | '/jellyfin'
    | '/login'
    | '/sessions'
    | '/sources'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/channels'
    | '/epg'
    | '/events'
    | '/jellyfin'
    | '/login'
    | '/sessions'
    | '/sources'
  id:
    | '__root__'
    | '/'
    | '/channels'
    | '/epg'
    | '/events'
    | '/jellyfin'
    | '/login'
    | '/sessions'
    | '/sources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChannelsRoute: typeof ChannelsRoute
  EpgRoute: typeof EpgRoute
  EventsRoute: typeof EventsRoute
  JellyfinRoute: typeof JellyfinRoute
  LoginRoute: typeof LoginRoute
  SessionsRoute: typeof SessionsRoute
  SourcesRoute: typeof SourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epg': {
      id: '/epg'
      path: '/epg'
      fullPath: '/epg'
      preLoaderRoute: typeof EpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jellyfin': {
      id: '/jellyfin'
      path: '/jellyfin'
      fullPath: '/jellyfin'
      preLoaderRoute: typeof JellyfinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChannelsRoute: ChannelsRoute,
  EpgRoute: EpgRoute,
  EventsRoute: EventsRoute,
  JellyfinRoute: JellyfinRoute,
  LoginRoute: LoginRoute,
  SessionsRoute: SessionsRoute,
  SourcesRoute: SourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
