[package]
name = "iptv-ingest"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
base64.workspace = true
bytes.workspace = true
chrono.workspace = true
flate2.workspace = true
futures-util.workspace = true
iptv-domain = { path = "../domain", version = "0.2.17" }
iptv-parsers = { path = "../parsers", version = "0.2.17" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true
uuid.workspace = true
xz2.workspace = true
zip.workspace = true

[dev-dependencies]
axum.workspace = true
iptv-persistence = { path = "../persistence", version = "0.2.17" }
tower.workspace = true

[lints]
workspace = true
